-- AlterTable
ALTER TABLE "Attempt" ADD COLUMN     "answers" JSONB DEFAULT '[]',
ADD COLUMN     "startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "warningCount" INTEGER NOT NULL DEFAULT 0;
